# Generated by Django 6.0 on 2026-01-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("paragraph", models.CharField(max_length=500)),
                ("slider_images", models.JSONField(default=list)),
            ],
        ),
    ]
