# Generated by Django 6.0 on 2026-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_section", "0002_remove_slider_slider_images_sliderimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
