# Generated by Django 6.0 on 2026-01-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Investment", "Investment"),
                            ("Energy", "Energy"),
                            ("Funds", "Funds"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="news/")),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
