# Generated by Django 6.0 on 2025-12-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="management/")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("senior associate", "Senior Associate"),
                            ("member", "Junior Officer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
